version: '2'
services:
  db:
    image: postgres:9.5
#    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
  web:
    build: .
#    command: bundle exec rails s -p 3000 -b '0.0.0.0'
#    restart: always
    volumes:
      - ./ap:/app
    ports:
      - "3000:3000"
    depends_on:
      - db
volumes:
  pgdata:
    external: false
